// Simple code generator that produces a C++ source file with a function
// that returns a vector of numbers.

#include <fstream>
#include <iostream>
#include <string>

int main(int argc, char *argv[]) {
    if (argc != 2) {
        std::cerr << "Usage: " << argv[0] << " <output_file>" << std::endl;
        return 1;
    }

    std::string output_path = argv[1];

    // Create output directory if needed
    auto last_slash = output_path.find_last_of("/\\");
    if (last_slash != std::string::npos) {
        // Note: In a real generator, you'd create the directory
        // CMake creates it for us when using add_custom_command
    }

    std::ofstream out(output_path);
    if (!out) {
        std::cerr << "Failed to open: " << output_path << std::endl;
        return 1;
    }

    out << "// Auto-generated by codegen - DO NOT EDIT\n";
    out << "#include <vector>\n";
    out << "#include <cstddef>\n";
    out << "\n";
    out << "std::vector<int> get_numbers() {\n";
    out << "    return {";
    for (int i = 1; i <= 10; ++i) {
        if (i > 1)
            out << ", ";
        out << i * i; // 1, 4, 9, 16, 25, 36, 49, 64, 81, 100
    }
    out << "};\n";
    out << "}\n";
    out << "\n";
    out << "std::size_t get_numbers_count() {\n";
    out << "    return 10;\n";
    out << "}\n";

    std::cout << "Generated: " << output_path << std::endl;
    return 0;
}
