// Main executable that uses the generated code

#include <iostream>
#include <vector>

// Functions generated by codegen executable
std::vector<int> get_numbers();
std::size_t get_numbers_count();

int main() {
    std::cout << "Numbers from generated code:" << std::endl;

    auto numbers = get_numbers();
    for (std::size_t i = 0; i < numbers.size(); ++i) {
        std::cout << "  numbers[" << i << "] = " << numbers[i] << std::endl;
    }

    // Verify the count
    if (numbers.size() == get_numbers_count()) {
        std::cout << "Success: Generated " << numbers.size() << " numbers!" << std::endl;
        return 0;
    } else {
        std::cerr << "Error: Count mismatch!" << std::endl;
        return 1;
    }
}
